<a href="https://colab.research.google.com/github/isa12-pixel/Estadistica/blob/main/Primer_Bono_Estad%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manejo de módulos integrados

NumPy: Se usa principalmente para trabajar con datos numéricos de forma rápida, eficiente y estructurada. Un objeto tipo numpy es un arreglo base para hacer matemáticas y manipular en Python.

Pandas se usa para trabajar con datos estructurados (Como tablas de Excel o bases de datos). Un objeto tipo para cargar, limpiar, transformar y analizar datos.

La diferencia entre NumPy y Pandas radica en su propósito y nivel de uso: NumPy es una librería enfocada en el cálculo numérico eficiente mediante arrays multidimensionales, ideal para operaciones matemáticas rápidas, álgebra lineal y procesamiento de datos puramente numéricos; mientras que Pandas es una librería de más alto nivel diseñada para la manipulación y análisis de datos estructurados como tablas tipo Excel o bases de datos, permitiendo trabajar con columnas con nombres, datos de distintos tipos, limpieza, filtrado y agrupación; en la práctica, Pandas se apoya internamente en NumPy, por lo que ambos se complementan y se utilizan juntos en la mayoría de flujos de ciencia de datos.

# Numpy

In [ ]:
import numpy as np

Creación de arreglos:

In [ ]:
a = np.array([8,2,7,4,2,6])
b = np.array([[14,3,7],[11,13,17]])
print(a)
print(b)

[8 2 7 4 2 6]
[[14  3  7]
 [11 13 17]]

In [ ]:
lista = [4, 8, 2]
arr = np.array([7,9,3])

In [ ]:
lista*2

[4, 8, 2, 4, 8, 2]

In [ ]:
arr*2
#Hay una interpretación de los arreglos de tipo numpy más apegados a lo que vemos de los objetos matemáticos como lo son los vectores.

array([14, 18,  6])

In [ ]:
b*2

array([[28,  6, 14],
       [22, 26, 34]])

In [ ]:
arr.shape
#Dimensión del arreglo.

(3,)

In [ ]:
b.shape
#Matriz de dos componentes cada una de tres elementos.
#Arreglo

(2, 3)

In [ ]:
arr.ndim
#Número de dimensiones
#Un elemento por cada una de las componentes.

1

In [ ]:
b.ndim #Número de elementos por cada componente
#Dos elementos por cada una de las componente.

2

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.size #Cantidad de elementos de todas las componentes

6

Creación de arreglos especiales:

In [ ]:
print(np.zeros((4,8)), #Arreglo de ceros
      np.ones((2,2)),  #Arreglo de unos
      np.eye(2),       #Arreglo de la matriz identidad
      np.arange(0, 14, 3), #Del 0 al 14 por 3
      np.linspace(0,2,5)) #Cinco valores equidistantes del 0 al 2

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] [[1. 1.]
 [1. 1.]] [[1. 0.]
 [0. 1.]] [ 0  3  6  9 12] [0.  0.5 1.  1.5 2. ]

In [ ]:
np.zeros((4,8)) #Todo lleno de ceros, cuatro componentes y ocho elementos por componente.

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,2)) #Todo lleno de unos: Dos componentes y dos elementos por componentes

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(2) #La matriz identidad de tamaño 2 * 2

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.arange(0, 14, 3) #Del 0 al 14 (Sin tomar el 14) separado por 3

array([ 0,  3,  6,  9, 12])

In [ ]:
np.linspace(0,2,5) #Toma cinco elementos equidistantes entre cero y dos

array([0. , 0.5, 1. , 1.5, 2. ])

Indexación

In [ ]:
arry = np.array([5, 10, 15, 20])
arry[0]

np.int64(5)

In [ ]:
arry[-1]

np.int64(20)

In [ ]:
arry[1:2] #Tomando del índice 1 al 2 sin tomar el 2

array([10])

Indexación de matrices

In [ ]:
matz = np.array([[0,2,8], [4,8,9]])
print(b[1,2], b[:,2], b[1,:])

17 [ 7 17] [11 13 17]

In [ ]:
matri=np.array([[0,2,8],[4,8,9]])

In [ ]:
matri[1,0] #El índice 0 de la 1-ésima fila

np.int64(4)

In [ ]:
matri[1,:]

array([4, 8, 9])

In [ ]:
a = np.array([7,29,10])
b = np.array([1,7,3])
a + b

array([ 8, 36, 13])

In [ ]:
a*b #Producto de Hadamard entre dos arreglos

array([  7, 203,  30])

In [ ]:
matri1 = np.array([[1,7,8], [4,8,9]])
matri1*matri #Producto de Hadamard

array([[ 0, 14, 64],
       [16, 64, 81]])

In [ ]:
[x*2 for x in lista]

[8, 16, 4]

In [ ]:
c = np.array([1, 5, 2, 8, 3])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

3.8 3.0 2.4819347291981715 19 1 8

Manipulación de arreglos

In [ ]:
d=np.array([7,5,12,1,4,0])#cambiar la forma,inicialmente tiene 6 componente de un elemento cada una
d.reshape(3,2) #cambia tres componentes cada una con 3 elementos

array([[ 7,  5],
       [12,  1],
       [ 4,  0]])

In [ ]:
np.concatenate([d,a])

array([ 7,  5, 12,  1,  4,  0,  7, 29, 10])

In [ ]:
np.concatenate(d.reshape(2,3))

array([ 7,  5, 12,  1,  4,  0])

In [ ]:
d.reshape(2,3).flatten() #Vectoriza la matriz

array([ 7,  5, 12,  1,  4,  0])

In [ ]:
a = np.array([[0,5], [7,8]])
b = np.array([[5,6], [2,0]]) #Producto punto

np.dot(a,b)

array([[10,  0],
       [51, 42]])

In [ ]:
np.linalg.det(a) #Determinante

np.float64(-34.99999999999999)

In [ ]:
np.linalg.inv(a) #Inversa

array([[-0.22857143,  0.14285714],
       [ 0.2       ,  0.        ]])

In [ ]:
np.linalg.matrix_transpose(a) #Transpuesta

array([[0, 7],
       [5, 8]])

In [ ]:
print(np.random.rand(12)) #Números aleatorios tipo float entre 0 y 1
print(np.random.randint(0,8)) #Números aletorios tipo int entre cero y el valor anterior a ocho (Distribución uniforme discreta).
print(np.random.rand(3)) #Tres valores aleatorios entre cero y uno (Intervalo) de una distribución uniforme

[0.85630563 0.11972342 0.5276843  0.87465964 0.4213144  0.25539622
 0.55878163 0.03403525 0.58536937 0.13768063 0.32770058 0.74823879]
5
[0.31676385 0.81551254 0.80013344]

In [ ]:
e = np.array([0,2,8,4,7]) #Filtrado y condiciones
e[e>3]

array([8, 4, 7])

In [ ]:
e[(e > 2) & (e < 8)]

array([4, 7])

In [ ]:
np.where(e>7, 0, 1) #e>7 nota 1 de lo contrario será cero

array([1, 1, 0, 1, 1])

In [ ]:
np.where(e>7, 0, e) #Valores que no se queiren reemplzar, anota el mismo objeto

array([0, 2, 0, 4, 7])

# Pandas

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([5, 10, 15]) #Vector columna
s

0     5
1    10
2    15
dtype: int64

In [ ]:
df=pd.DataFrame({
    'nombre' : ['Jimin','Tae','RM','Jin',"Yoongi"],
    'ciudad' : ['Busan','Seúl','Daegu','Jeonju','Ulsan'],
    'edad' : [33,30,30,31,33],
    'salario' : [50000,30000,45000,45000,50000]
}) # de diccionario a data.frames
df

   nombre  ciudad  edad  salario
0   Jimin   Busan    33    50000
1     Tae    Seúl    30    30000
2      RM   Daegu    30    45000
3     Jin  Jeonju    31    45000
4  Yoongi   Ulsan    33    50000

In [ ]:
df.head(1) #Primera fila

  nombre ciudad  edad  salario
0  Jimin  Busan    33    50000

In [ ]:
df.info() #tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   5 non-null      object
 1   ciudad   5 non-null      object
 2   edad     5 non-null      int64
 3   salario  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe() #Estadísticas descriptivas básicas para variables cuantitativas

            edad       salario
count   5.000000      5.000000
mean   31.400000  44000.000000
std     1.516575   8215.838363
min    30.000000  30000.000000
25%    30.000000  45000.000000
50%    31.000000  45000.000000
75%    33.000000  50000.000000
max    33.000000  50000.000000

In [ ]:
df.shape #(Filas, columnas)

(5, 4)

In [ ]:
salario_promedio = df['salario'].mean()
print(f"El salario promedio es: {salario_promedio}")

El salario promedio es: 44000.0

In [ ]:
df['edad']

0    33
1    30
2    30
3    31
4    33
Name: edad, dtype: int64

In [ ]:
df[['nombre', 'edad']] #Selección de columnas utilizandp una lista con los respectivos nombres

   nombre  edad
0   Jimin    33
1     Tae    30
2      RM    30
3     Jin    31
4  Yoongi    33

In [ ]:
df[df['edad']>30 & (df['edad']<20)]

   nombre  ciudad  edad  salario
0   Jimin   Busan    33    50000
1     Tae    Seúl    30    30000
2      RM   Daegu    30    45000
3     Jin  Jeonju    31    45000
4  Yoongi   Ulsan    33    50000

In [ ]:
data={
    'nombre' : ['Jimin','Tae','RM','Jin',"Yoongi", None],
    'ciudad' : ['Busan','Seúl','Daegu','Jeonju','Ulsan'],
    'edad' : [33,np.nan, 30,30,31,33],
    'salario' : [50000,30000,45000,45000,None, 50000]
}
data

{'nombre': ['Jimin', 'Tae', 'RM', 'Jin', 'Yoongi', None],
 'ciudad': ['Busan', 'Seúl', 'Daegu', 'Jeonju', 'Ulsan'],
 'edad': [33, nan, 30, 30, 31, 33],
 'salario': [50000, 30000, 45000, 45000, None, 50000]}

In [ ]:
data1= pd.DataFrame(data)
data1

   nombre  ciudad  edad  salario
0   Jimin   Busan  33.0  50000.0
1     Tae    Seúl   NaN  30000.0
2      RM   Daegu  30.0  45000.0
3     Jin  Jeonju  30.0  45000.0
4  Yoongi   Ulsan  31.0      NaN
5    None    None  33.0  50000.0

In [ ]:
data1.isnull() #Valores faltantes (TRUE= Faltante)

   nombre  ciudad   edad  salario
0   False   False  False    False
1   False   False   True    False
2   False   False  False    False
3   False   False  False    False
4   False   False  False     True
5    True    True  False    False

In [ ]:
data1.isnull().sum() #Suma los valores faltantes por columna

nombre     1
ciudad     1
edad       1
salario    1
dtype: int64

In [ ]:
data2 = data1.dropna() #Elimina las filas con valores faltantes
data2

  nombre  ciudad  edad  salario
0  Jimin   Busan  33.0  50000.0
2     RM   Daegu  30.0  45000.0
3    Jin  Jeonju  30.0  45000.0

In [ ]:
data1.dropna(subset=['salario'])#Elimana las filas con valores faltantes únicamente en la columna salario

  nombre  ciudad  edad  salario
0  Jimin   Busan  33.0  50000.0
1    Tae    Seúl   NaN  30000.0
2     RM   Daegu  30.0  45000.0
3    Jin  Jeonju  30.0  45000.0
5   None    None  33.0  50000.0

In [ ]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean()) #Rellena los valores faltantes con la media
data1['nombre'] = data1['nombre'].fillna("Desconocido")
data1

        nombre  ciudad  edad  salario
0        Jimin   Busan  33.0  50000.0
1          Tae    Seúl  31.4  30000.0
2           RM   Daegu  30.0  45000.0
3          Jin  Jeonju  30.0  45000.0
4       Yoongi   Ulsan  31.0      NaN
5  Desconocido    None  33.0  50000.0

In [ ]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean()) #reemplaza los valores faltantes por la media
data1['nombre'] = data1['nombre'].fillna('Desconocido') #reemplaza los valores faltantes por Desconocido
data1['salario'] = data1['salario'].fillna(data1['salario'].mean()) #reemplaza los valores faltantes por la media
data1

        nombre  ciudad  edad  salario
0        Jimin   Busan  33.0  50000.0
1          Tae    Seúl  31.4  30000.0
2           RM   Daegu  30.0  45000.0
3          Jin  Jeonju  30.0  45000.0
4       Yoongi   Ulsan  31.0  44000.0
5  Desconocido    None  33.0  50000.0

In [ ]:
data1['ciudad']= data1['ciudad'].replace('Busan','BucaramanGa')
data1

        nombre       ciudad  edad  salario
0        Jimin  Bucaramanga  33.0  50000.0
1          Tae         Seúl  31.4  30000.0
2           RM        Daegu  30.0  45000.0
3          Jin       Jeonju  30.0  45000.0
4       Yoongi        Ulsan  31.0  44000.0
5  Desconocido         None  33.0  50000.0

In [ ]:
data4= data1['ciudad'].drop_duplicates() #Elimina los valores duplicados
data4

0    Bucaramanga
1           Seúl
2          Daegu
3         Jeonju
4          Ulsan
5           None
Name: ciudad, dtype: object

In [ ]:
data5={
    'nombre' : ['Jimin','Tae','RM','Jin',"Yoongi"],
    'ciudad' : ['Busan','Seúl','Daegu','Jeonju','Ulsan'],
    'edad' : [33, 30,30,31,33],
    'salario' : [50000,30000,45000,45000,50000]
}
data5= pd.DataFrame(data5)
data5

   nombre  ciudad  edad  salario
0   Jimin   Busan    33    50000
1     Tae    Seúl    30    30000
2      RM   Daegu    30    45000
3     Jin  Jeonju    31    45000
4  Yoongi   Ulsan    33    50000

In [ ]:
data6=data5.drop_duplicates()
data6

   nombre  ciudad  edad  salario
0   Jimin   Busan    33    50000
1     Tae    Seúl    30    30000
2      RM   Daegu    30    45000
3     Jin  Jeonju    31    45000
4  Yoongi   Ulsan    33    50000

In [ ]:
dfn=pd.DataFrame({
    'id' : [0,1,2,3,4],
    'nombre' : ['Jimin','Tae','RM','Jin',"Yoongi"],
    'ciudad' : ['Busan','Seúl','Daegu','Jeonju','Ulsan'],
    'edad' : [33, 30,30,31,33],
    'salario' : [50000,30000,45000,45000,50000]
})
dfn

   id  nombre  ciudad  edad  salario
0   0   Jimin   Busan    33    50000
1   1     Tae    Seúl    30    30000
2   2      RM   Daegu    30    45000
3   3     Jin  Jeonju    31    45000
4   4  Yoongi   Ulsan    33    50000

In [ ]:
dfn['salario_anual']=dfn['salario']*12
#aplicar funcion
dfn['edad_doble']=dfn['edad'].apply(lambda x:x*2)
dfn

   id  nombre  ciudad  edad  salario  salario_anual  edad_doble
0   0   Jimin   Busan    33    50000         600000          66
1   1     Tae    Seúl    30    30000         360000          60
2   2      RM   Daegu    30    45000         540000          60
3   3     Jin  Jeonju    31    45000         540000          62
4   4  Yoongi   Ulsan    33    50000         600000          66

In [ ]:
dfn=dfn.rename(columns={'edad':'age'})
dfn

   id  nombre  ciudad  age  salario  salario_anual  edad_doble
0   0   Jimin   Busan   33    50000         600000          66
1   1     Tae    Seúl   30    30000         360000          60
2   2      RM   Daegu   30    45000         540000          60
3   3     Jin  Jeonju   31    45000         540000          62
4   4  Yoongi   Ulsan   33    50000         600000          66

In [ ]:
dfn['nombre']=dfn['nombre'].str.upper()
dfn['nombre']=dfn['nombre'].str.strip()
dfn['nombre']=dfn['nombre'].str.replace('GABRIELA','GABRIEL')
dfn

   id  nombre  ciudad  age  salario  salario_anual  edad_doble
0   0   JIMIN   Busan   33    50000         600000          66
1   1     TAE    Seúl   30    30000         360000          60
2   2      RM   Daegu   30    45000         540000          60
3   3     JIN  Jeonju   31    45000         540000          62
4   4  YOONGI   Ulsan   33    50000         600000          66

In [ ]:
grupo=dfn.groupby('ciudad')['salario'].mean() # Toma los elemento de la ciudad, y se calcula la media aritmetica
grupo

ciudad
Busan     50000.0
Daegu     45000.0
Jeonju    45000.0
Seúl      30000.0
Ulsan     50000.0
Name: salario, dtype: float64

In [ ]:
ordenado=dfn.sort_values(by='age') # ordena por la edad de menor a mayor
ordenado

   id  nombre  ciudad  age  salario  salario_anual  edad_doble
1   1     TAE    Seúl   30    30000         360000          60
2   2      RM   Daegu   30    45000         540000          60
3   3     JIN  Jeonju   31    45000         540000          62
0   0   JIMIN   Busan   33    50000         600000          66
4   4  YOONGI   Ulsan   33    50000         600000          66

In [ ]:
valores=dfn.values #pasar de un objeto pandas a un arreglo
valores

array([[0, 'JIMIN', 'Busan', 33, 50000, 600000, 66],
       [1, 'TAE', 'Seúl', 30, 30000, 360000, 60],
       [2, 'RM', 'Daegu', 30, 45000, 540000, 60],
       [3, 'JIN', 'Jeonju', 31, 45000, 540000, 62],
       [4, 'YOONGI', 'Ulsan', 33, 50000, 600000, 66]], dtype=object)

In [ ]:
arr=np.array([20,40,50])
df=pd.DataFrame(arr) #pasar de un arreglo a pandas
df

    0
0  20
1  40
2  50